[package]
authors = ["simdimdim <simdimdim@gmail.com>"]
default-run = "main"
edition = "2018"
name = "pagepal-ui"
resolver = "2"
version = "0.1.0"

[dependencies]
iced = {git = "https://github.com/hecrj/iced", features = ["tokio", "debug"]}
iced_native = {git = "https://github.com/hecrj/iced"}

reqwest = "0.11.4"
url = { version = "2.2.2", features = ["serde"] }

chrono = { version = "0.4.19", features = ["serde"] }
directories-next = "2.0.0"
itertools = "0.10.1"
rand = "0.8.4"

serde = "1.0.126"

futures = "0.3.15"
[dependencies.tokio]
features = ["fs", "time", "net", "macros", "rt-multi-thread"]
version = "1.7.1"
