[workspace]
# "pagepal",
members = ["retriever", "bibliotheca", "storage"]
resolver = "2"

[workspace.dependencies]
futures = "0.3.31"
rand = "0.8.5"
rayon = "1.10.0"
time = "0.3.37"

# TODO: migrate to tracing
[workspace.dependencies.env_logger]
default-features = true # colorized
version = "0.11.5" 
[workspace.dependencies.dashmap]
# features = ["rayon","inline"]
features = ["rayon"]
version = "6.1.0"
[workspace.dependencies.log]
features = ["release_max_level_off"]
version = "0.4.22"
[workspace.dependencies.reqwest]
features = ["stream", "cookies", "gzip"]
version = "0.12.9"
[workspace.dependencies.serde]
features = ["derive"]
version = "1.0.215"
[workspace.dependencies.tokio]
default-features = false
features = ["fs", "time", "net", "macros", "rt-multi-thread"]
version = "1.42.0"
[workspace.dependencies.url]
features = ["serde"]
version = "2.5.4"
