[package]
name = "pagepal-ui"
version = "0.1.0"
edition = "2018"
resolver = "2"
default-run = "main"
authors = ["simdimdim <simdimdim@gmail.com>"]

[dependencies]
iced = {git = "https://github.com/hecrj/iced", features = ["tokio", "debug"]}
iced_native = {git = "https://github.com/hecrj/iced"}

url = { version = "2.2.2", features = ["serde"] }
reqwest = "0.11.4"

itertools= "0.10.1"
directories-next = "2.0.0"
rand = "0.8.4"

chrono = { version = "0.4.19", features = ["serde"] }
futures = "0.3.15"
[dependencies.tokio]
features = ["fs", "time", "net", "macros", "rt-multi-thread"]
version = "1.7.1"
