unstable_features = true
version = "Two"

brace_style = "PreferSameLine"
color = "Always"
comment_width = 82
indent_style = "Block"
max_width = 82

binop_separator = "Back"
empty_item_single_line = true
enum_discrim_align_threshold = 30
inline_attribute_width = 82
overflow_delimited_expr = true
struct_field_align_threshold = 30

imports_layout = "HorizontalVertical"
imports_granularity="Crate"
reorder_impl_items = true
reorder_imports = true
reorder_modules = true

# fn_args_layout = "Vertical"
fn_args_layout = "Compressed"
# fn_params_layout = "Compressed" # #4163
fn_single_line = true
force_multiline_blocks = false

wrap_comments = true
# format_code_in_doc_comments = true

use_field_init_shorthand = true
use_try_shorthand = true

# hide_parse_errors=true
