unstable_features = true
version = "Two"

brace_style = "PreferSameLine"
color = "Always"
indent_style = "Block"

binop_separator = "Back"
empty_item_single_line = true
overflow_delimited_expr = true

imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
reorder_impl_items = true
reorder_imports = true
reorder_modules = true

# fn_args_layout = "Vertical"
fn_args_layout = "Compressed"
# fn_params_layout = "Compressed" # #4163
fn_single_line = true
force_multiline_blocks = false

format_code_in_doc_comments = true
use_field_init_shorthand = true
use_try_shorthand = true

# hide_parse_errors=true
